fix(ui): convert to numeric literals for blueprint-compiler >= 0.6
error: Cannot convert string to number
at ../data/ui/setup_window.blp line 308 column 25:
 308 |          maximum-size: "400";
     |                        ^

error: Cannot convert string to number
at ../data/ui/setup_window.blp line 309 column 33:
 309 |          tightening-threshold: "200";
     |                                ^